POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "ravid1233@gmail.com",
    "password": "Testing123!@#"
}

###

POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgzYWNhODQ1YjZiNDM4NTdjMjIzZWUiLCJpYXQiOjE2NTI4MTUwOTJ9.4Yz6spaCgdjYFSo_ICdvsDBCxAIFK2ZOpk48IZnIQ7o"
}

###

DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgzYWNhODQ1YjZiNDM4NTdjMjIzZWUiLCJpYXQiOjE2NTI4MTUwOTJ9.4Yz6spaCgdjYFSo_ICdvsDBCxAIFK2ZOpk48IZnIQ7o"
}

###