GET http://localhost:5000/api/products

###

GET http://localhost:5000/api/products/627d24d57aa7daed90ac6406

###

POST http://localhost:5000/api/products
Content-Type: application/json

{
    "name": "test",
    "description": "a short description",
    "price": 345,
    "countInStock": 2,
    "imageUrl": "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80"
}

###

PUT http://localhost:5000/api/products/62837719c887e9cc01436888
Content-Type: application/json

{
    "name": "test1234",
    "description": "a short description",
    "price": 345,
    "countInStock": 2,
    "imageUrl": "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80"
}

###

DELETE http://localhost:5000/api/products/62837778702cf9e6d8e33bd0
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgzYWNhODQ1YjZiNDM4NTdjMjIzZWUiLCJpYXQiOjE2NTI4MDAzMDB9.hdSJmlqPU1gGTc-1xCLYrVAK27xN-xzmq1xmGrT5F2I
###